CONFIG_PRINTK=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
 
CONFIG_POLL=y

CONFIG_VIDEO=y
CONFIG_VIDEO_SYNA_MIPI=y
CONFIG_VIDEO_SYNA_ENC=y
CONFIG_VIDEO_INIT_PRIORITY=90
CONFIG_VIDEO_SYNA_MIPI_INIT_PRIORITY=110

CONFIG_FPU=y
CONFIG_MAIN_STACK_SIZE=6144
CONFIG_CMSIS_RTOS_V2=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_INIT_STACKS=y
CONFIG_NUM_PREEMPT_PRIORITIES=56
# XSPI storage is optional (CONFIG_STORE_TO_XSPI)
