CONFIG_BT=y
CONFIG_LOG=y
CONFIG_BT_CLASSIC=y
CONFIG_BT_RFCOMM=y
CONFIG_BT_HFP_HF=y
CONFIG_BT_DEVICE_NAME="SR110 Handsfree"
CONFIG_BT_COD=0x200408
CONFIG_BT_DID=y
CONFIG_BT_DEVICE_VEDNOR_ID=0x0000
CONFIG_BT_DEVICE_PRODUCT_ID=0x0001
CONFIG_BT_DEVICE_VERSION=0x0001
CONFIG_BT_CONN_TX_MAX=15
CONFIG_BT_BUF_ACL_RX_SIZE=1024

# SR110 + SYNA hardware
CONFIG_BT_H4=y
CONFIG_BT_HCI_SYNA=y
CONFIG_GPIO=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_XIP=n
CONFIG_SRAM_SIZE=512
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_BT_RX_STACK_SIZE=4096
CONFIG_BT_BUF_CMD_TX_SIZE=255
CONFIG_BT_HCI_ACL_FLOW_CONTROL=n
CONFIG_LOG_PRINTK=n

# Logging
CONFIG_BT_HFP_HF_LOG_LEVEL_DBG=y
CONFIG_BT_RFCOMM_LOG_LEVEL_INF=y
CONFIG_BT_SDP_LOG_LEVEL_INF=y
CONFIG_BT_L2CAP_LOG_LEVEL_INF=y
CONFIG_BT_HCI_CORE_LOG_LEVEL_INF=y

# Disable unsupported features
CONFIG_SHELL=n
CONFIG_MBEDTLS_PSA_CRYPTO_C=n
