manifest:
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: 36681aa631ada56a9f5511c0f56be31ea5fa055b
      path: zephyr
      west-commands: scripts/west-commands.yml
      import:
        name-allowlist:
          - cmsis_6
          - fatfs

  self:
    path: zephyr_srsdk
