CONFIG_USERSPACE=y
CONFIG_ASSERT=y

# Shell configuration
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_SHELL_STACK_SIZE=8192
CONFIG_BOOT_BANNER=y
CONFIG_SHELL_PROMPT_UART="Srw1500:$ "
CONFIG_SHELL_HISTORY=y
CONFIG_SHELL_HISTORY_BUFFER=512

# Syscounter
# Slowclock timer
# Timer
CONFIG_COUNTER=y

# GPIO
CONFIG_GPIO=y

# I2C
CONFIG_I2C=y

# SPI
CONFIG_SPI=y

# Watchdog
CONFIG_WATCHDOG=y

# OTP Provisioning
CONFIG_OTP_PROVISIONED_ENABLED=n
CONFIG_OTP_PROVISIONED_V2_ENABLED=n
CONFIG_OTP_PROVISIONED_DISABLED=y

# File System
CONFIG_FILE_SYSTEM=y
CONFIG_FILE_SYSTEM_SHELL=y

# RAM FS
CONFIG_FILE_SYSTEM_MKFS=y
CONFIG_DISK_DRIVERS=y
CONFIG_FAT_FILESYSTEM_ELM=y

# Pinctrl
CONFIG_PINCTRL=y
CONFIG_PINCTRL_DYNAMIC=y
