CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
# Avoid Kconfig warnings from board defaults pulling in I2C shell options.
CONFIG_I2C_SHELL=n
CONFIG_FPU=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_PINCTRL=y
CONFIG_VIDEO=y
CONFIG_VIDEO_SYNA_ENC=y
CONFIG_VIDEO_SYNA_MIPI=n
CONFIG_VIDEO_INIT_PRIORITY=90

# Two 128 KiB buffers + overhead (give headroom).
CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=524288

CONFIG_MAIN_STACK_SIZE=4096
