CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_LOG_BACKEND_SHOW_TIMESTAMP=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_MBOX=y
CONFIG_THREAD_NAME=y
CONFIG_EVENTS=y
CONFIG_GPIO=y
CONFIG_INPUT=y
CONFIG_I2C=y

# USB CDC ACM and HID composite support on HOST.
CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_HID_SUPPORT=y
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_USBD_MAX_SPEED_FULL=y
CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n
CONFIG_USBD_BOS_SUPPORT=n
CONFIG_USBD_VREQ_SUPPORT=n
CONFIG_UDC_BUF_POOL_SIZE=2048
CONFIG_USBD_MAX_UDC_MSG=8
CONFIG_USBD_MSG_SLAB_COUNT=8
CONFIG_USBD_HWINFO_DEVID_LENGTH=8
CONFIG_USBD_THREAD_STACK_SIZE=2048
CONFIG_UDC_DWC2_STACK_SIZE=2048
CONFIG_USBD_LOG_LEVEL_ERR=y
CONFIG_USBD_HID_LOG_LEVEL_ERR=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_ERR=y
CONFIG_UDC_DRIVER_LOG_LEVEL_ERR=y
CONFIG_SAMPLE_USBD_PID=0x0007
CONFIG_SAMPLE_USBD_PRODUCT="USBD CDC ACM & HID sample"

CONFIG_USB_HID_LAYER=y
CONFIG_USB_HID_KEYBOARD=y
CONFIG_USB_HID_MOUSE=y
CONFIG_USB_HID_PROFILES_ALL=y
CONFIG_USB_HID_ALS=y
CONFIG_USB_HID_PTP=y
CONFIG_USB_HID_TSP=y
CONFIG_USB_HID_CUSTOM=y
CONFIG_USB_HID_HUMAN_PRESENCE=y
CONFIG_USB_HID_GENERIC_ALGO=y
