CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_MAIN_STACK_SIZE=65536
CONFIG_REQUIRES_FLOAT_PRINTF=y
CONFIG_SIZE_OPTIMIZATIONS=y
# Ethos-U55 NPU
CONFIG_ETHOS_U=y
CONFIG_ETHOS_U55_128=y
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_LOG=y
