CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_VIDEO=y
CONFIG_VIDEO_INIT_PRIORITY=60
CONFIG_VIDEO_SYNA_MIPI=y
CONFIG_VIDEO_SYNA_MIPI_INIT_PRIORITY=110
CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=400000
CONFIG_VIDEO_BUFFER_POOL_ALIGN=64
CONFIG_I2C_SHELL=n

CONFIG_FPU=y

CONFIG_HEAP_MEM_POOL_SIZE=200000

CONFIG_CMSIS_RTOS_V2=y
CONFIG_POLL=y
CONFIG_THREAD_NAME=y
CONFIG_THREAD_STACK_INFO=y
CONFIG_THREAD_MONITOR=y
CONFIG_INIT_STACKS=y
CONFIG_NUM_PREEMPT_PRIORITIES=56

CONFIG_PRINTK=y
CONFIG_LOG_MODE_IMMEDIATE=y
