#CONFIG_WATCHDOG=y
CONFIG_XIP=n
CONFIG_SHELL_STACK_SIZE=4096
#CONFIG_CPU_LOAD=y
#CONFIG_CPU_LOAD_LOG_PERIODICALLY=1000
CONFIG_THREAD_RUNTIME_STATS=y

CONFIG_WIFI_4612=y
CONFIG_WIFI=y
CONFIG_SHELL=y
CONFIG_WIFI_SYNA=y
CONFIG_TIMER_RANDOM_GENERATOR=y
CONFIG_SDIO_STACK=y
CONFIG_SDHC_MSHC=y

CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NET_L2_WIFI_MGMT=y

CONFIG_NETWORKING=y
CONFIG_NET_SHELL_IP_SUPPORTED=y
CONFIG_NET_SHELL_DHCPV4_SUPPORTED=y
CONFIG_NET_CONNECTION_MANAGER=y

CONFIG_NET_SOCKETS=y
CONFIG_NET_IPV4=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_DHCPV4_SERVER=y

CONFIG_NET_UDP=y
CONFIG_NET_TCP=y
CONFIG_NET_MAX_CONN=64
CONFIG_NET_BUF=y
CONFIG_NET_PKT_RX_COUNT=200
CONFIG_NET_PKT_TX_COUNT=200
CONFIG_NET_BUF_RX_COUNT=200
CONFIG_NET_BUF_TX_COUNT=200
CONFIG_NET_CONTEXT_NET_PKT_POOL=y

#CONFIG_NET_LOG=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_NET_IF_UNICAST_IPV4_ADDR_COUNT=2
CONFIG_NET_SHELL=y
#CONFIG_LOG_PRINTK=y
#CONFIG_LOG=y
CONFIG_MAIN_STACK_SIZE=2048
CONFIG_NET_IF_MAX_IPV4_COUNT=2
CONFIG_POSIX_API=y

#CONFIG_NET_BUF_LOG=y
#CONFIG_NET_TX_STACK_SIZE=8192
#CONFIG_NET_RX_STACK_SIZE=8192
CONFIG_NET_BUF_DATA_SIZE=2048
CONFIG_NET_TCP_MAX_SEND_WINDOW_SIZE=65000
CONFIG_NET_TCP_MAX_RECV_WINDOW_SIZE=65000
CONFIG_NET_IPV4_FRAGMENT=y
CONFIG_NET_IPV4_FRAGMENT_MAX_COUNT=15
CONFIG_NET_IPV4_FRAGMENT_MAX_PKT=15
CONFIG_NET_IPV4_FRAGMENT_TIMEOUT=15

#CONFIG_NET_TC_TX_COUNT=1
#CONFIG_NET_TC_RX_COUNT=1
###### net threads priority
#CONFIG_NET_TC_THREAD_PRIO_CUSTOM=y
#CONFIG_NET_TC_RX_THREAD_BASE_PRIO=2

CONFIG_NET_TC_THREAD_PREEMPTIVE=y
#CONFIG_NET_TC_THREAD_COOPERATIVE=y
CONFIG_NET_TCP_WORKER_PRIO=1
#CONFIG_NET_TC_TX_THREAD_BASE_PRIO=-1
