CONFIG_CPP=y
CONFIG_STD_CPP17=y
CONFIG_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_TENSORFLOW_LITE_MICRO=y
CONFIG_MAIN_STACK_SIZE=65536
CONFIG_SIZE_OPTIMIZATIONS=y
CONFIG_FPU=y
# Ethos-U55 NPU
CONFIG_ETHOS_U=y
CONFIG_ETHOS_U55_128=y
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_LOG=n

CONFIG_VIDEO=y
CONFIG_VIDEO_INIT_PRIORITY=90
CONFIG_VIDEO_SYNA_MIPI=y
CONFIG_VIDEO_SYNA_ENC=y
CONFIG_VIDEO_SYNA_MIPI_INIT_PRIORITY=110
CONFIG_VIDEO_BUFFER_POOL_HEAP_SIZE=320000
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=4
CONFIG_VIDEO_BUFFER_POOL_ALIGN=64
CONFIG_POLL=y

CONFIG_GPIO=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y
CONFIG_REBOOT=y

CONFIG_USB_DEVICE_STACK_NEXT=y
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n
CONFIG_USBD_CDC_ACM_CLASS=y
CONFIG_USBD_MAX_SPEED_FULL=y
CONFIG_UDC_DRIVER_HIGH_SPEED_SUPPORT_ENABLED=n
CONFIG_USBD_BOS_SUPPORT=n
CONFIG_USBD_VREQ_SUPPORT=n
CONFIG_UDC_BUF_POOL_SIZE=2048
CONFIG_USBD_MAX_UDC_MSG=8
CONFIG_USBD_MSG_SLAB_COUNT=8
CONFIG_USBD_HWINFO_DEVID_LENGTH=8
CONFIG_USBD_THREAD_STACK_SIZE=2048
CONFIG_UDC_DWC2_STACK_SIZE=2048
CONFIG_USBD_LOG_LEVEL_ERR=y
CONFIG_UDC_DRIVER_LOG_LEVEL_ERR=y
CONFIG_USBD_CDC_ACM_LOG_LEVEL_ERR=y

CONFIG_SERVICE_HOST_API_ENABLED=y
CONFIG_SERVICE_USB_HOST_API_ENABLED=y
CONFIG_SERVICE_SYSTEM_ENABLED=y
CONFIG_SERVICE_UC_MANAGER_ENABLED=y
CONFIG_ACTIVE_INTERFACE_USB=y
CONFIG_HOST_API_AUTO_START=y
CONFIG_HOST_API_USB_VID=0xCAFE
CONFIG_HOST_API_USB_PID=0x4002
CONFIG_HOST_API_THREAD_STACK_SIZE=4096
CONFIG_HOST_API_TASK_PRIORITY=5
CONFIG_HOST_API_SDK_VER_MAJOR=0
CONFIG_HOST_API_SDK_VER_MINOR=9
CONFIG_HOST_API_SDK_VER_REVISION=7
